"""Insight data classes."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, Any, Optional
from enum import Enum


class Severity(Enum):
    """Severity levels for insights."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class InsightType(Enum):
    """Types of insights."""
    RISK = "risk"
    OPPORTUNITY = "opportunity"
    ANOMALY = "anomaly"
    TREND = "trend"
    RECOMMENDATION = "recommendation"


@dataclass
class Insight:
    """
    Represents a single business insight generated by an analyst check.
    
    Attributes:
        check_name: Name of the check that generated this insight
        title: Short title describing the insight
        description: Detailed description
        severity: Severity level
        insight_type: Type of insight
        metrics: Key metrics that support this insight
        recommendation: Recommended action (optional)
        timestamp: When the insight was generated
        metadata: Additional context-specific data
    """
    check_name: str
    title: str
    description: str
    severity: Severity
    insight_type: InsightType
    metrics: Dict[str, Any]
    recommendation: Optional[str] = None
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert insight to dictionary for serialization."""
        return {
            "check_name": self.check_name,
            "title": self.title,
            "description": self.description,
            "severity": self.severity.value,
            "insight_type": self.insight_type.value,
            "metrics": self.metrics,
            "recommendation": self.recommendation,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
        }

