"""Base class for analyst checks."""

from abc import ABC, abstractmethod
from typing import List, Dict, Any
from business_analyst.core.insight import Insight
from business_analyst.context.base import BusinessContext


class AnalystCheck(ABC):
    """
    Abstract base class for all analyst checks.
    
    Each check is self-contained and can be added/removed without
    modifying other checks. Checks use business context to make
    industry-specific judgments.
    """
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Return the name of this check."""
        pass
    
    @property
    @abstractmethod
    def description(self) -> str:
        """Return a description of what this check does."""
        pass
    
    @abstractmethod
    def execute(
        self,
        features: Dict[str, Any],
        context: BusinessContext
    ) -> List[Insight]:
        """
        Execute the analyst check.
        
        Args:
            features: Extracted features from raw data
            context: Business context for industry-specific rules
            
        Returns:
            List of insights generated by this check
            
        Raises:
            CheckExecutionError: If check execution fails
        """
        pass
    
    def is_applicable(self, context: BusinessContext) -> bool:
        """
        Check if this check is applicable to the given context.
        
        Override this method to make checks industry-specific.
        By default, all checks are applicable to all industries.
        
        Args:
            context: Business context
            
        Returns:
            True if check is applicable, False otherwise
        """
        return True

